sudo: required
services:
  - docker

before_install:
  - docker build -t brunomiquelotto/react-app-docker-ci -f Dockerfile.dev .

script:
  - docker run -e CI=true brunomiquelotto/react-app-docker-ci npm run test -- --coverage