sudo: required
services:
  - docker

before_install:
  - docker build -t brunomiquelotto/react-app-docker-ci -f Dockerfile.dev .

script:
  - docker run -e CI=true brunomiquelotto/react-app-docker-ci npm run test -- --coverage

deploy:
  provider: elasticbeanstalk 
  region: "us-east-2"
  app: "react-app-docker-ci"
  env: "ReactAppDockerCi-env"
  bucket_name: "elasticbeanstalk-us-east-2-686169929009"
  bucket_path: "react-app-docker-ci"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_ACCESS_SECRET"